version: '3.8'

# networks:
#   dev:
#     driver: bridge

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ROOT_PASSWORD: 'minio_password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tango-malena
    restart: always
    ports:
      - "5433:5432"
    # networks:
    #   - dev

  web:
    build:
      dockerfile: Dockerfile
      context: .
    #image: docprojdevplant:latest
    depends_on:
      - "db"
    container_name: web-services
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__Default=Host=db;Port=5433;Username=your_username;Password=your_password;Database=your_database_name;Pooling=true;
      - ASPNETCORE_URLS=http://+:8080

    # networks:
    #   - dev

