name: docprojdevplant
services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ROOT_PASSWORD: 'minio_password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data

  db:
    #trebuie scris in terminalul din container ./restore.sh
    build:
      context: ./Database
      dockerfile: Dockerfile.db
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=docprojdevplant
    restart: always
    ports:
      - "5432:5432"
    # command: pg_restore -U postgres -d docprojdevplant testdb.tar

  libreoffice:
    build:
      context: ./LibreOffice
      dockerfile: Dockerfile.libre
    ports:
      - "5000:5000"
    container_name: libreoffice


  # web:
  #   build:
  #     context: ./Backend
  #     dockerfile: Dockerfile.backend
  #   depends_on:
  #     - "db"
  #   container_name: web-services
  #   ports:
  #     - "8080:8080"